server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: diary-service
          uri: lb://diary-service
          predicates:
            - Path=/diaries/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081

